[project]
name = "cryosparc-tools"
version = "0.1.0"
description = "Toolkit for interfacing with cryoSPARC"
authors = [
    { name = "Structura Biotechnology Inc.", email = "info@structura.bio"}
]
requires-python = ">=3.7"
dependencies = [
    "numpy ~= 1.20",
    "typing-extensions >= 3.7",
]

[project.optional-dependencies]
dev = [
    "build",
    "pytest ~= 5.2",
    "black ~= 22.3.0",
    "httpretty ~= 1.1.4"
]

[tool.setuptools]
packages = ["cryosparc", "src"]  # FIXME: Rename src -> cryosparc_dataset or similar

[build-system]
requires = ["setuptools", "numpy"]
build-backend = "setuptools.build_meta"
