[tool.poetry]
name = "cryosparc-tools"
version = "0.1.0"
description = "Toolkit for interfacing with cryoSPARC"
authors = ["Structura Biotechnology Inc. <info@structura.bio>"]
packages = [
    { include = "cryosparc" }
]

[tool.poetry.dependencies]
python = ">=3.7"
numpy = ">=1.20,<2"
typing-extensions = ">=3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.3.0"
httpretty = "^1.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
