[project]
name = "cryosparc-tools"
version = "0.1.0"
description = "Toolkit for interfacing with cryoSPARC"
authors = [
    { name = "Structura Biotechnology Inc.", email = "info@structura.bio"}
]
requires-python = ">=3.7"
dependencies = [
    "numpy ~= 1.20",
    "python-snappy ~= 0.6",
    "typing-extensions >= 3.7",
]

[project.optional-dependencies]
dev = [
    "build",
    "jupyter-book ~= 0.13",
    "pytest ~= 7.1",
    "pytest-benchmark ~= 3.4",
    "pytest-xdist[psutil] ~= 2.5.0",
    "black[jupyter] ~= 22.3.0",
    "httpretty ~= 1.1.4"
]

[tool.setuptools]
packages = ["cryosparc"]

[build-system]
requires = ["setuptools", "numpy"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
