[project]
name = "cryosparc-tools"
version = "0.1.0"
description = "Toolkit for interfacing with CryoSPARC"
authors = [
    { name = "Structura Biotechnology Inc.", email = "info@structura.bio"}
]
requires-python = ">=3.7"
dependencies = [
    "numpy ~= 1.15",
    "python-snappy ~= 0.6",
    "typing-extensions >= 3.7",
]

[project.optional-dependencies]
dev = [
    "build",
    "black",
    "cython",
    "httpretty",
    "pyright",
    "pytest-benchmark",
    "pytest-xdist[psutil]",
    "pytest",
    "ruff",
]

build = [
    "build",
    "autodocsumm",
    "jupyter-book",
]

examples = [
    "pandas == 1.1.4",
    "matplotlib >=3.4<3.5",
    "numpy >=1.18<1.19",
    "black[jupyter] ~= 22.3.0",
    "cryolo[c11]",
    "notebook",
]

[tool.setuptools]
packages = ["cryosparc"]

[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["cryosparc", "tests", "setup.py"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
exclude = ["docs"]
